# Generated by Django 3.1.1 on 2020-09-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'existent'), (1, 'deleted')])),
                ('content', models.TextField()),
            ],
        ),
    ]
