# Generated by Django 3.0.7 on 2020-11-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_doc', '0002_auto_20201026_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
