# Generated by Django 3.0.7 on 2020-11-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_doc', '0004_document_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='src',
            field=models.TextField(default=''),
        ),
    ]
