# Generated by Django 3.0.7 on 2020-10-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0002_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='这个人很懒，什么都没留下~', max_length=500),
        ),
    ]
